config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  get 'say/filenames' # Adding route

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
    # @files = Dir.glob('*')
  end

  def filenames #adding filenames method
    @files = Dir.glob('*')
    @foo = "bar"
    # return @files
  end

  def goodbye

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/filenames.html.erb
<p>The files in the current directory are:</p>
<ul>
  <% for file in @files %>
  <li><%= file %></li>
  <% end %>
</ul>
<p>This is foo: <%= @foo %></p>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here!</p>
<p>Say <%=link_to "Hello", say_hello_path%> again.</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>It is now <%= @time %> </p>
<p>Let's try some math: 1+2 = <%=1+2%></p>
<p>Also we are going to concatenate: cow and boy <%= "cow" + "boy"%></p>
<p>The time in an hour will be: <%=1.hour.from_now.localtime %></p>
<br>
<p>This is foo: <%= @foo %></p>

<p>Time to say <%= link_to ("Goodbye"), say_goodbye_path %>!</p>